name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  TAGS: "-tags=czmq4"

jobs:
  main:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
        go-version: [1.24.x, 1.23.x]

    runs-on: ${{ matrix.platform }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
          cache: true

      - name: Install Linux packages
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update -qq -y
          sudo apt-get install -y libsodium-dev libczmq-dev

      - name: Install macOS packages
        if: matrix.platform == 'macos-latest'
        run: |
          brew install libsodium czmq

      - name: go install
        run: go install -v ${{ env.TAGS }} ./...

      - name: Test with coverage
        if: matrix.platform == 'ubuntu-latest'
        run: ./.ci/code-coverage.sh

      - name: Test
        if: matrix.platform != 'ubuntu-latest'
        run: go test -race ${{ env.TAGS }} ./...

      - name: Verify code formatting
        run: |
          test -z $(gofmt -l .)

      - name: Run linter
        uses: dominikh/staticcheck-action@v1
        with:
          install-go: false
          cache-key: ${{ matrix.platform }}
          version: "2023.1"

      - name: Upload code coverage
        uses: codecov/codecov-action@v3
